services:
    opennamu-web:
        container_name: opennamu-web
        # image: opennamu:latest
        build:
            context: .
            dockerfile: Dockerfile.ko
        ports:
            - "3000:3000"
        volumes:
            - ./docker_data:/app/data
        environment:
            NAMU_DB_TYPE: mysql
            NAMU_DB: data
            NAMU_DB_HOST: opennamu-db
            NAMU_DB_PORT: 3306
            NAMU_DB_USER: opennamu
            NAMU_DB_PASSWORD: opennamu_password
            NAMU_LANG: ko-KR
            NAMU_MARKUP: namumark
        networks:
            - opennamu
        depends_on:
            - opennamu-db

    opennamu-db:
        container_name: opennamu-db
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: data
            MYSQL_USER: opennamu
            MYSQL_PASSWORD: opennamu_password
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - opennamu

networks:
    opennamu:
