package main

import "github.com/gin-gonic/gin"

func register_routes(r *gin.Engine) {
	register_access_routes(r)
	register_api_routes(r)
	register_api_compat_routes(r)
	register_api_block_compat_routes(r)
	register_watch_routes(r)
	register_record_compat_routes(r)
	register_record_page_compat_routes(r)
	register_api_post_routes(r)
	register_api_watch_post_routes(r)
	register_list_routes(r)
	register_list_extra_routes(r)
	register_auth_routes(r)
	register_user_compat_routes(r)
	register_user_routes(r)
	register_alarm_routes(r)
	register_login_routes(r)
	register_register_routes(r)
	register_wiki_routes(r)
	register_wiki_compat_routes(r)
	register_recent_routes(r)
	register_vote_routes(r)
	register_bbs_routes(r)
	register_thread_routes(r)
	register_history_edit_routes(r)
	register_document_extra_routes(r)
	register_search_compat_routes(r)
	register_search_routes(r)
	register_manager_routes(r)
	register_filter_routes(r)
	register_admin_routes(r)
	register_admin_misc_routes(r)
	register_list_compat_routes(r)
	register_server_routes(r)
	register_setting_routes(r)
}
