package main

import "github.com/gin-gonic/gin"

func Register_routes(r *gin.Engine) {
	Register_access_routes(r)
	Register_captcha_routes(r)
	Register_api_routes(r)
	Register_api_compat_routes(r)
	Register_api_block_compat_routes(r)
	Register_watch_routes(r)
	Register_record_compat_routes(r)
	Register_record_page_compat_routes(r)
	Register_api_post_routes(r)
	Register_api_watch_post_routes(r)
	Register_list_routes(r)
	Register_list_extra_routes(r)
	Register_user_multiple_routes(r)
	Register_auth_routes(r)
	Register_user_tool_routes(r)
	Register_user_compat_routes(r)
	Register_user_routes(r)
	Register_store_routes(r)
	Register_point_routes(r)
	Register_alarm_routes(r)
	Register_login_routes(r)
	Register_register_routes(r)
	Register_wiki_routes(r)
	Register_wiki_compat_routes(r)
	Register_category_routes(r)
	Register_auth_give_list_routes(r)
	Register_recent_routes(r)
	Register_vote_routes(r)
	Register_bbs_routes(r)
	Register_bbs_search_routes(r)
	Register_thread_routes(r)
	Register_image_routes(r)
	Register_history_edit_routes(r)
	Register_document_extra_routes(r)
	Register_include_routes(r)
	Register_search_compat_routes(r)
	Register_search_routes(r)
	Register_ollama_routes(r)
	Register_document_backup_routes(r)
	Register_manager_routes(r)
	Register_filter_routes(r)
	Register_admin_routes(r)
	Register_admin_misc_routes(r)
	Register_list_compat_routes(r)
	Register_server_routes(r)
	Register_setting_routes(r)
}
