package tool

type Auth_choice struct {
	Level int
	Key   string
	Lang  string
}

func Auth_choices() []Auth_choice {
	return []Auth_choice{
		{1, "owner", "owner_authority"},
		{1, "user", "user_authority"},
		{2, "rankup", "rankup_authority"},
		{2, "do_email_verified", "do_email_verified_authority"},
		{2, "captcha_pass", "captcha_pass_authority"},
		{2, "ip", "ip_authority"},
		{3, "document", "document_authority"},
		{4, "edit", "edit_authority"},
		{5, "edit_limit_10", "edit_limit_10_authority"},
		{5, "edit_limit_50", "edit_limit_50_authority"},
		{5, "edit_limit_100", "edit_limit_100_authority"},
		{5, "edit_limit_unlimited", "edit_limit_unlimited_authority"},
		{4, "move", "move_authority"},
		{4, "new_make", "new_make_authority"},
		{4, "delete", "delete_authority"},
		{4, "view", "view_authority"},
		{4, "image_view", "image_view_authority"},
		{5, "site_view", "site_view_authority"},
		{3, "discuss", "discuss_authority"},
		{4, "discuss_make_new_thread", "discuss_make_new_thread_authority"},
		{4, "discuss_view", "discuss_view_authority"},
		{3, "upload", "upload_authority"},
		{3, "vote", "vote_authority"},
		{3, "bbs_use", "bbs_authority"},
		{4, "bbs_edit", "bbs_edit_authority"},
		{5, "bbs_edit_limit_10", "bbs_edit_limit_10_authority"},
		{5, "bbs_edit_limit_50", "bbs_edit_limit_50_authority"},
		{5, "bbs_edit_limit_100", "bbs_edit_limit_100_authority"},
		{5, "bbs_edit_limit_unlimited", "bbs_edit_limit_unlimited_authority"},
		{4, "bbs_comment", "bbs_comment_authority"},
		{5, "bbs_comment_limit_10", "bbs_comment_limit_10_authority"},
		{5, "bbs_comment_limit_50", "bbs_comment_limit_50_authority"},
		{5, "bbs_comment_limit_100", "bbs_comment_limit_100_authority"},
		{5, "bbs_comment_limit_unlimited", "bbs_comment_limit_unlimited_authority"},
		{4, "bbs_view", "bbs_view_authority"},
		{3, "captcha_one_check_five_pass", "captcha_one_check_five_pass_authority"},
		{3, "edit_filter_view", "edit_filter_view_authority"},
		{1, "admin", "admin_authority"},
		{2, "email_verified", "email_verified_acl"},
		{2, "up_to_level_10", "up_to_level_10"},
		{3, "up_to_level_3", "up_to_level_3"},
		{2, "trust_d", "trust_d_acl"},
		{3, "trust_c", "trust_c_acl"},
		{4, "trust_a", "trust_a_acl"},
		{5, "large_edit", "large_edit_authority"},
		{4, "trust_b", "trust_b_acl"},
		{2, "login_available", "login_available_authority"},
		{2, "register_available", "register_available_authority"},
		{2, "edit_filter_manage", "edit_filter_manage_authority"},
		{2, "application_manage", "application_manage_authority"},
		{2, "application_view", "application_view_authority"},
		{2, "toron", "discussion_authority"},
		{2, "check", "user_analyze_authority"},
		{2, "view_user_watchlist", "view_user_watchlist_authority"},
		{2, "acl", "document_acl_authority"},
		{2, "hidel", "history_hide_authority"},
		{2, "give_range", "authorization_range_authority"},
		{3, "give", "authorization_authority"},
		{2, "bbs", "bbs_management_authority"},
		{2, "vote_fix", "vote_management_authority"},
		{2, "admin_default_feature", "admin_default_feature_authority"},
		{2, "setting_main", "setting_main_authority"},
		{2, "setting_main_logo", "setting_main_logo_authority"},
		{2, "setting_skin", "setting_skin_authority"},
		{2, "setting_head", "setting_head_authority"},
		{2, "setting_top_menu", "setting_top_menu_authority"},
		{2, "setting_phrase", "setting_phrase_authority"},
		{2, "setting_external", "setting_external_authority"},
		{2, "setting_robot", "setting_robot_authority"},
		{2, "setting_sitemap", "setting_sitemap_authority"},
		{2, "setting_404", "setting_404_authority"},
		{2, "setting_backlink", "setting_backlink_authority"},
		{2, "setting_delete", "setting_delete_authority"},
		{2, "setting_manage", "setting_manage_authority"},
		{2, "setting_email_test", "setting_email_test_authority"},
		{2, "server_action", "server_action_authority"},
		{2, "auth_group_manage", "auth_group_manage_authority"},
		{2, "auth_fix", "auth_fix_authority"},
		{2, "rankup_manage", "rankup_manage_authority"},
		{2, "history_view", "history_view_authority"},
		{2, "history_manage", "history_manage_authority"},
		{2, "record_manage", "record_manage_authority"},
		{2, "user_manage", "user_manage_authority"},
		{2, "file_delete", "file_delete_authority"},
		{2, "document_acl_manage", "document_acl_manage_authority"},
		{2, "document_bulk_delete", "document_bulk_delete_authority"},
		{2, "document_move_manage", "document_move_manage_authority"},
		{2, "filter_manage", "filter_manage_authority"},
		{2, "user_edit_filter_manage", "user_edit_filter_manage_authority"},
		{2, "bbs_post_manage", "bbs_post_manage_authority"},
		{2, "auth_private_give", "auth_private_give_authority"},
		{2, "bbs_create", "bbs_create_authority"},
		{2, "bbs_main_view", "bbs_main_view_authority"},
		{2, "bbs_manage", "bbs_manage_authority"},
		{2, "bbs_setting", "bbs_setting_authority"},
		{2, "bbs_delete", "bbs_delete_authority"},
		{2, "bbs_pin", "bbs_pin_authority"},
		{2, "bbs_comment_manage", "bbs_comment_manage_authority"},
		{2, "thread_manage", "thread_manage_authority"},
		{2, "thread_change", "thread_change_authority"},
		{2, "thread_delete", "thread_delete_authority"},
		{2, "thread_setting", "thread_setting_authority"},
		{2, "thread_acl", "thread_acl_authority"},
		{2, "thread_comment_manage", "thread_comment_manage_authority"},
		{2, "thread_comment_delete", "thread_comment_delete_authority"},
		{2, "vote_manage", "vote_manage_authority"},
		{2, "manager_view", "manager_view_authority"},
		{3, "doc_watch_list_view", "doc_watch_list_view_authority"},
		{3, "treat_as_admin", "treat_as_admin_authority"},
		{3, "view_hide_user_name", "view_hide_user_name_authority"},
		{3, "user_name_bold", "user_name_bold_authority"},
		{3, "multiple_upload", "multiple_upload_authority"},
		{3, "slow_edit_pass", "slow_edit_pass_authority"},
		{3, "edit_bottom_compulsion_pass", "edit_bottom_compulsion_pass_authority"},
		{3, "edit_filter_pass", "edit_filter_pass_authority"},
		{3, "nothing", "nothing_authority"},
	}
}
